# Generated by Django 5.0.1 on 2024-02-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='category',
        ),
        migrations.AddField(
            model_name='problem',
            name='category',
            field=models.ManyToManyField(related_name='problems', to='problems.problemcategory'),
        ),
    ]
