# Generated by Django 5.0.1 on 2024-03-28 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_problem_category_problem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='problemcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='userproblemstatus',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='problems.problem'),
        ),
    ]
