export const PROBLEMS_SUCCESS = 'PROBLEMS_SUCCESS'
export const PROBLEMS_LOADING = 'PROBLEMS_LOADING'
export const PROBLEMS_FAIL = 'PROBLEMS_FAIL'

export const PROBLEM_SUCCESS = 'PROBLEM_SUCCESS'
export const PROBLEM_LOADING = 'PROBLEM_LOADING'
export const PROBLEM_FAIL = 'PROBLEM_FAIL'

export const USER_PROBLEM_CODE_SAVE_SUCCESS = 'USER_PROBLEM_CODE_SAVE_SUCCESS'
export const USER_PROBLEM_CODE_SAVE_LOADING = 'USER_PROBLEM_CODE_SAVE_LOADING'
export const USER_PROBLEM_CODE_SAVE_FAIL = 'USER_PROBLEM_CODE_SAVE_FAIL'

export const PROBLEMS_SAVED_SUCCESS = 'PROBLEMS_SAVED_SUCCESS'
export const PROBLEMS_SAVED_LOADING = 'PROBLEMS_SAVED_LOADING'
export const PROBLEMS_SAVED_FAIL = 'PROBLEMS_SAVED_FAIL'