export const SUBMISSION_SUCCESS = 'SUBMISSION_SUCCESS'
export const SUBMISSION_LOADING = 'SUBMISSION_LOADING'
export const SUBMISSION_FAIL = 'SUBMISSION_FAIL'

export const SUBMISSIONS_GET_LOADING = 'SUBMISSIONS_GET_LOADING'
export const SUBMISSIONS_GET_SUCCESS = 'SUBMISSIONS_GET_SUCCESS'
export const SUBMISSIONS_GET_FAIL = 'SUBMISSIONS_GET_FAIL'
